### PR TITLE
Refactor Spain country handler to support Natural Persons without DNI or NIE and Non-Natural Persons TIN formats

### PR DESCRIPTION
**Pull request by alphp**
Rebased changes of #36

### CODE REVIEW

**Comment by drupol** [comment]
Sad you opened a new PR :( but OK I'll give my final thoughts tomorrow.

**Comment by alphp** [comment]
I can't express my anger at having to do it like this after so much work.
But this week has been very complicated both personally and professionally: I can't take it anymore.

**Comment by drupol** [comment]
I can take care of it if you want, so we don't loose the history? Are you OK if I do it myself?

**Comment by alphp** [comment]
That would be great.
Thank you so much for all your patience with me.

**Comment by drupol** [comment]
> That would be great. Thank you so much for all your patience with me.

No problem, can you check if I have the right to push to your branch?

**Pull request merged**
